version: '3.9'

services:
  web:
    build: ./
    command: uvicorn src.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/code
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0