services:
  web:
    build: ./
    command: uvicorn src.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ${PWD}:/code
      - ${PWD}/static:/static
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVEN_API_KEY=${ELEVEN_API_KEY}
    secrets:
      - openai_api_key
      - eleven_api_key

secrets:
   openai_api_key:
     file: ./.key
   eleven_api_key:
     file: ./.elevenapikey